include(
    ":app",
    ":common",
    ":domain",
    ":data:remote",
    ":data:model",
    ":data:local",
    ":data:repository",
    ":features:home",
    ":features:detail",
    ":common_test",
    ":navigation"
)
